# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
export PATH="/k/xampp/bin:/k/xampp/php:/k/xampp/ruby/bin/:$PATH"
export PATH="/k/PortableApps/NodeJSPortable/App/NodeJS:/k/PortableApps/NodeJSPortable/Data:$PATH"
alias phpcs="/k/xampp/bin/phpcs --colors"
alias phpcbf="/k/xampp/bin/phpcbf --colors"
alias netbeans="/k/PortableApps/NetBeansPortable/NetBeansPHPPortable.exe&"
alias papercut="/k/xampp/papercut/Papercut.exe&"
